In [1]:
import numpy as np 
x = np.array([3, 4, 5])
y = np.array([4, 9, 7]) 
z = x + y 
z

array([ 7, 13, 12])

In [18]:
x = np.array([[1,2,6],[3,4,5]])
x.ndim
x.dtype

dtype('int32')

In [ ]:
np.array?

In [21]:
x = np.array([[1,2,6],[3,4,5]])
x.shape

(2, 3)

In [23]:
x = np.array([[1,2,6],[3,4,5]])
x.dtype

dtype('int32')

In [53]:
np.random.normal(size=3)

array([ 1.13042727,  0.73887142, -2.12431592])

In [163]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

np.corrcoef(x, y)

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


array([[ 1.        , -0.14447532],
       [-0.14447532,  1.        ]])